### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by jkufner** [ondratu/formiko#1]
README says:

> Formiko have Vim editor support aka formiko-vim command. This run Vim editor in GtkSocket. At this
> moment, this socket work only on X11 backend, so this is not work on Wayland yet.

It would be much better to use [Neovim](https://neovim.io/) and its [msgpack-rpc API](https://github.com/neovim/neovim/blob/master/runtime/doc/msgpack_rpc.txt) ([Python client](https://github.com/neovim/python-client)). It would avoid the use of the X11-only GtkSocket and could provide much better Vim integration.

**Comment by ondratu** [comment]
next tip for study https://github.com/neovim/python-gui

**Comment by ondratu** [comment]
Although modification on vim code is not at the end, it is work now in Vte.terminal on X11 and on Wayland too.
