### ISSUE TITLE
Numbered list not displayed correctly

### ISSUE THREAD

**Issue by patrickdung** [ondratu/formiko#17]
Sample rst (also attached as test.rst in this ticket)

```
=============
List of items
=============

1. Point one

- eggs
- milk
- apples

2. Point two

   Test.

   *Test*

3. Point Three

   Test.
```

The numbered list is not in order (1. 2. 3.). It is displayed as (1. 1. 2.)

Gitit (that should use pandoc) and http://rst.ninjs.org could display the numbered list correctly.

Formiko and Retext (https://github.com/retext-project/retext) could not display the numbered list in order.
[test.rst.txt](https://github.com/ondratu/formiko/files/3908176/test.rst.txt)

**Comment by patrickdung** [comment]
David Goodger (Docutil's author) replies that bullet list should be indented to indicate that it is part of item 1. See
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#indentation

So it's not a bug of formiko.

**Comment by ondratu** [comment]
Thanks
