### ISSUE TITLE
Unreadable Text w/ Dark Theme

### ISSUE THREAD

**Issue by mmstick** [ondratu/formiko#18]
Hyperlinks are being rendered with a dark blue color on a dark background, making them unreadable.

**Comment by ondratu** [comment]
I have idea how i can fix this, but could you tell me how you get black render page? I got always white. So which interface you use to get black page, or how you set it. Did you use own css style?

Thanks for your report.

**Comment by ondratu** [comment]
Some additional style ideas is here: https://github.com/ondratu/formiko/commit/24d466d20120317d984ddfec2d1180c51b581817

**Comment by ondratu** [comment]
Renderer has default background and color from Gtk.TextView now. https://github.com/ondratu/formiko/commit/c3667f4da36023351edc679f953b1f0f1a49ab10
![Snímek z 2022-03-29 21-04-35](https://user-images.githubusercontent.com/6469029/160687636-3e5301c3-eff4-4085-9d96-6b885f84312e.png)
