### ISSUE TITLE
Using links to navigate between local files

### ISSUE THREAD

**Issue by david-libremone** [ondratu/formiko#2]
**User story:** I am editing a collection of cross-linked Markdown files. When I click on a relative link, it should be treated as a local file link, so that I can jump between files while editing.

**Suggested solution:** When clicking on a relative link in Preview pane, close the current file and open the target file. (If the current file has not been saved, first prompt to save.)

**Alternate solution:** When clicking on a relative link in Preview pane, open the target file in a new Formiko instance. (If such an instance already exists, bring it to the foreground.)

**Notes:** At the moment the relative link opens the target file in the Preview pane. This means it appears but cannot be edited.

**Comment by ondratu** [comment]
As I comment issue #9 , this is done by some merged pull requests. So if you are OK with that, i will close this issue on release.
