### ISSUE TITLE
Preview is slightly weird

### ISSUE THREAD

**Issue by VMGuy23** [ondratu/formiko#33]
Instead of opening links in a browser, it opens it in itself. 
![dsff](https://user-images.githubusercontent.com/81651922/116893091-7960fa00-ac28-11eb-9b83-379426ea2635.png)

**Comment by VMGuy23** [comment]
And yes, I did make the issue from within the editor

**Comment by ondratu** [comment]
Hi, did you please tell me, which version you are use? I try it simple in version from git master branch, and link is opened in my browser. May by, this error is in some special case, which I don't know now. Please can you send me some example document, which do this?

**Comment by VMGuy23** [comment]
I got it from the Ubuntu APT repo. Maybe that needs to be updated.

**Comment by ondratu** [comment]
Yes, this was be fixed. Please try to version from git (master or some tagged release).

And yes, i'm working on update package in Debian and Ubuntu now.

**Comment by VMGuy23** [comment]
Nice. Will close now.
