### ISSUE TITLE
Common Mark option is grayed out 

### ISSUE THREAD

**Issue by darenw** [ondratu/formiko#37]
On my Arch Linux machine, in the settings drop-down, "Common Mark parser" is grayed out. Apparently it's necessary for viewing .md files.  Why? It is not clear. I guessed that I needed to install cmark, but doing so did not help. Perhaps some other package for dealing with markdown or commonmark?

On a nearby Ubuntu machine, I installed formiko (using synaptic) and it shows .md files just fine.  Works great!  Using the common mark option in settings.  Interesting: cmark is not installed. 

What is different between the Arch machine and the Ubuntu machine?  What to install on Arch to un-gray that option?

**Comment by ondratu** [comment]
I was add some additional information to option tool-tips: https://github.com/ondratu/formiko/commit/4f100d0f877a3063f0a7a1ecbf8da078a1ed03ad
