### ISSUE TITLE
Question regarding code blocks

### ISSUE THREAD

**Issue by frgomes** [ondratu/formiko#4]
Hello, I've tried something like this:

    .. code-block:: python
       :linenos:

... which complains like this:

    System Message: ERROR/3 (<string>, line 11)
    Error in "code-block" directive: maximum 1 argument(s) allowed, 2 supplied.

Am I missing something?
By the way... it's Formiko 1.3.0 on Debian Buster. More info below:

    $ uname -a
    Linux lua 4.18.0-1-amd64 #1 SMP Debian 4.18.6-1 (2018-09-06) x86_64 GNU/Linux

    $ cat /etc/os-release 
    PRETTY_NAME="Debian GNU/Linux buster/sid"
    NAME="Debian GNU/Linux"
    ID=debian
    HOME_URL="https://www.debian.org/"
    SUPPORT_URL="https://www.debian.org/support"
    BUG_REPORT_URL="https://bugs.debian.org/"
    
    $ sudo apt install formiko -y 
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following additional packages will be installed:
      gir1.2-gtkspell3-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-webkit2-4.0 libgtkspell3-3-0 python3-commonmark-bkrs python3-recommonmark
    Suggested packages:
      vim-gtk3 python-commonmark-bkrs-doc
    The following NEW packages will be installed:
      formiko gir1.2-gtkspell3-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-webkit2-4.0 libgtkspell3-3-0 python3-commonmark-bkrs python3-recommonmark
    0 upgraded, 7 newly installed, 0 to remove and 10 not upgraded.
    Need to get 0 B/372 kB of archives.
    After this operation, 1,360 kB of additional disk space will be used.
    Selecting previously unselected package libgtkspell3-3-0:amd64.
    (Reading database ... 235960 files and directories currently installed.)
    Preparing to unpack .../0-libgtkspell3-3-0_3.0.9-2_amd64.deb ...
    Unpacking libgtkspell3-3-0:amd64 (3.0.9-2) ...
    Selecting previously unselected package gir1.2-gtkspell3-3.0:amd64.
    Preparing to unpack .../1-gir1.2-gtkspell3-3.0_3.0.9-2_amd64.deb ...
    Unpacking gir1.2-gtkspell3-3.0:amd64 (3.0.9-2) ...
    Selecting previously unselected package gir1.2-javascriptcoregtk-4.0:amd64.
    Preparing to unpack .../2-gir1.2-javascriptcoregtk-4.0_2.22.0-2_amd64.deb ...
    Unpacking gir1.2-javascriptcoregtk-4.0:amd64 (2.22.0-2) ...
    Selecting previously unselected package gir1.2-webkit2-4.0:amd64.
    Preparing to unpack .../3-gir1.2-webkit2-4.0_2.22.0-2_amd64.deb ...
    Unpacking gir1.2-webkit2-4.0:amd64 (2.22.0-2) ...
    Selecting previously unselected package python3-commonmark-bkrs.
    Preparing to unpack .../4-python3-commonmark-bkrs_0.5.4+ds-1_all.deb ...
    Unpacking python3-commonmark-bkrs (0.5.4+ds-1) ...
    Selecting previously unselected package python3-recommonmark.
    Preparing to unpack .../5-python3-recommonmark_0.4.0+ds-2_all.deb ...
    Unpacking python3-recommonmark (0.4.0+ds-2) ...
    Selecting previously unselected package formiko.
    Preparing to unpack .../6-formiko_1.3.0-1_all.deb ...
    Unpacking formiko (1.3.0-1) ...
    Processing triggers for mime-support (3.61) ...
    Processing triggers for desktop-file-utils (0.23-3) ...
    Setting up python3-commonmark-bkrs (0.5.4+ds-1) ...
    Setting up gir1.2-javascriptcoregtk-4.0:amd64 (2.22.0-2) ...
    Processing triggers for libc-bin (2.27-6) ...
    Setting up python3-recommonmark (0.4.0+ds-2) ...
    Setting up libgtkspell3-3-0:amd64 (3.0.9-2) ...
    Processing triggers for hicolor-icon-theme (0.17-2) ...
    Setting up gir1.2-webkit2-4.0:amd64 (2.22.0-2) ...
    Setting up gir1.2-gtkspell3-3.0:amd64 (3.0.9-2) ...
    Setting up formiko (1.3.0-1) ...
    Processing triggers for libc-bin (2.27-6) ...
    Scanning processes...
    Scanning processor microcode...
    Scanning linux images...
    Running kernel seems to be up-to-date.
    The processor microcode seems to be up-to-date.
    No services need to be restarted.
    No containers need to be restarted.
    No user sessions are running outdated binaries.

Thanks

**Comment by ondratu** [comment]
Hi, that is docutils error.

I know, that ``code-block`` works, but i can't found them on resturctured text help pages, i use only ``code``. And i really don't know, what ``linenos`` could to do. When you can create lines output, there is ``number-lines`` option. See http://docutils.sourceforge.net/docs/ref/rst/directives.html#code.
