### ISSUE TITLE
[BUG]gir1.2-webkit2-4.0 

### ISSUE THREAD

**Issue by Fr-Dae** [ondratu/formiko#44]
**on Lubuntu 24.04**
E: Le paquet « gir1.2-webkit2-4.0 » n'a pas de version susceptible d'être installée
`E: The "gir1.2-webkit2-4.0" package has no version that can be installed`
work with gir1.2-webkit2-4.1

**Comment by ondratu** [comment]
I have to check all dependecies, so i reopen this issue

**Comment by Fr-Dae** [comment]
check your email =)

**Comment by Fr-Dae** [comment]
not link to a PR ?

**Comment by ondratu** [comment]
Oh... you are right. I publish new release 1.5.0: 49a8cff128ae82ebc23918f2b44acfe8b703e260 when your commit: d1dcfe3c5fd9fd7445aceb5caa8a8f0074951dc1 is included. 

There is no problem with new Webkit library, and in next days i plan to refactor and rewrite app to new libraries only (GTK4, GtkSourceView 5, and so on)

**Comment by Fr-Dae** [comment]
at right on github you have a button "make a branch from this issue" auto closed when the pr it's merge. and enable the fonction "auto release chagnelog" if you add tag for you release =)
make clean and easy the work 
have a nice day

(you can link issue manually to PR too, in "developpenment" icon

**Comment by Fr-Dae** [comment]
> Oh... you are right. I publish new release 1.5.0: [49a8cff](https://github.com/ondratu/formiko/commit/49a8cff128ae82ebc23918f2b44acfe8b703e260) when your commit: [d1dcfe3](https://github.com/ondratu/formiko/commit/d1dcfe3c5fd9fd7445aceb5caa8a8f0074951dc1) is included.
> 
> There is no problem with new Webkit library, and in next days i plan to refactor and rewrite app to new libraries only (GTK4, GtkSourceView 5, and so on)

On lubuntu we use GTK3 not sure about 4
