### ISSUE TITLE
let me disable spell checking

### ISSUE THREAD

**Issue by medovina** [ondratu/formiko#5]
It's nice that Formiko has spell checking for people who want it.  But for those of us who don't, it's an unnecessary distraction.  Please add an option to disable spell checking - thanks!

**Comment by ondratu** [comment]
You can disable spell check in pop up menu from application status bar.
![snimek z 2018-10-15 11-13-39](https://user-images.githubusercontent.com/6469029/46941469-7bafd880-d06b-11e8-8a82-7b0a49e11204.png)

**Comment by medovina** [comment]
Ah, thanks!
