### ISSUE TITLE
Does not render hard line break

### ISSUE THREAD

**Issue by scruloose** [ondratu/formiko#8]
I'm using formiko 1.3.0 installed on a Debian Bullseye system from the official Debian repos. Package python3-recommonmark version 0.4.0 is also installed from official Debian repos.

According to the CommonMark spec, ending a line with a backslash "\\" should result in a hard line-break "\<br /\>" in the parsed output.

However, in formiko, ending a line on a backslash, or space-then-backslash, or two spaces, has no effect. The text simply continues on the same line, unless I leave a blank line to start a new paragraph. As far as I can tell, there is no way to insert a line break except by typing in the whole html \<br /\> tag every time, which is both inconvenient and ugly.

I don't know whether this is a formiko bug, or a bug in the recommonmark library, but the absence of this fundamental formatting capability is a hindrance to formiko's usefulness.

**Comment by ondratu** [comment]
Hi, thank's for bug report,

but as you write this is not formiko bug/support, but recommonmark bug/support. As i tested, with new version of recommonmark from pypi (version 0.6.0), it works. I just upgrade recommonmark with pypi:

```sh
pip3 install -U recommonmark
```

If you do as normal user, only your user have this functionality, if you do as root, all users in system will have this functionality ;)

Thanks for using, and have a nice day! :-)
